### ISSUE TITLE
Typo in BLGtoSQL.ps1

### ISSUE THREAD

**Issue by Samantha-Harrison** [heraflux/BLGtoSQL#3]
(https://github.com/heraflux/BLGtoSQL/blob/664ce53d8038869746beaf1a3d657d0526c4bebb/BLGtoSQL.ps1#L88)
I believe this line should show 'csv' not 'tsv' see below:
`get-childitem $PerfmonDirectory -recurse -Filter "*.blg"  | % { relog $_.FullName -f csv -y -o ($_.FullName -Replace (".blg",".csv")) } | out-null`

**Comment by BobPusateri** [comment]
Actually, "tsv" is indeed correct. Some Perfmon counters have commas in their names, and their presence causes things to break when using CSV. 

TSV uses tabs instead of commas, so the commas in Perfmon counters won't cause issues.
